name: Sync CSV from Google Drive

on:
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar gdown e baixar o CSV
      run: |
        pip install gdown
        gdown --id 1a8DjJ9bkHZKoJvzfcDHR54EAymHXUFTw -O Db_Pacotes_Enjoei.csv

    - name: Commit e Push CSV Atualizado
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
        git add Db_Pacotes_Enjoei.csv
        git diff --cached --quiet || git commit -m "🔄 Atualização automática do CSV"
        git push origin HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
